M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu22.10.1} date Sun 16 Apr 2023 07:26:30 PM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-16T19:26:30-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu22.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
%
G90
G05
T1
X4.8051Y-1.1513
X5.0807Y-1.1513
T0
M30
